package components;

import java.awt.Color;
import spdvi.gestionart.models.Comentari;

/**
 *
 * @author DevMike
 */
public class ComentariComponent extends javax.swing.JPanel {

    public void setComentari(Comentari comentari) {
        lblNomUsuari.setText(comentari.getNom());
        
        txaTextComentari.setOpaque(false);
        txaTextComentari.setEditable(false);
        txaTextComentari.setBackground(new Color(0,0,0,0));
        txaTextComentari.setLineWrap(true);
        txaTextComentari.setWrapStyleWord(true);
        txaTextComentari.setRows(1);
        if (comentari.getText().length() <= 200) {
            txaTextComentari.setText(comentari.getText());        
        }
        else {
            txaTextComentari.setText(comentari.getText().substring(0, 200) + "..."); 
            txaTextComentari.setToolTipText("<html><p width=\"300\">" +comentari.getText()+"</p></html>");
        }

        lblComentariDate.setText(comentari.getDataihora().toString());
    }
   
    /**
     * Creates new form ComentariComponent
     */
    public ComentariComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfilePicture = new javax.swing.JLabel();
        lblNomUsuari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblComentariDate = new javax.swing.JLabel();
        txaTextComentari = new javax.swing.JTextArea();

        lblProfilePicture.setText("jLabel1");
        lblProfilePicture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblNomUsuari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomUsuari.setForeground(new java.awt.Color(51, 51, 51));
        lblNomUsuari.setText("Maria Arbona Sureda");

        jLabel2.setText("dijo:");

        lblComentariDate.setForeground(new java.awt.Color(102, 102, 102));
        lblComentariDate.setText("On Tuesday 18 Jan 2022");

        txaTextComentari.setColumns(20);
        txaTextComentari.setRows(1);
        txaTextComentari.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblComentariDate)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProfilePicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomUsuari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(txaTextComentari, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomUsuari)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaTextComentari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblComentariDate)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblComentariDate;
    private javax.swing.JLabel lblNomUsuari;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JTextArea txaTextComentari;
    // End of variables declaration//GEN-END:variables
}
