/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package spdvi.gestionart.dialogs;

import components.ComentariComponent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import spdvi.gestionart.Constants;
import spdvi.gestionart.Models.Espai;
import spdvi.gestionart.dataaccess.DataAccess;
import spdvi.gestionart.models.Comentari;
import spdvi.gestionart.utils.SessionSingleton;

/**
 *
 * @author DevMike
 */
public class EspaiDetailsDialog extends javax.swing.JDialog {

    Espai espai;

    /**
     * Creates new form EspaiDetailsDialog
     */
    public EspaiDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SessionSingleton session = SessionSingleton.INSTANCE.getInstance();
        if (session.getUsuari() != null) {
            pnlNewComment.setEnabled(true);
        }
        else {
            pnlNewComment.setEnabled(false);
        }
    }

    public EspaiDetailsDialog(java.awt.Frame parent, boolean modal, Espai espai) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.espai = espai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcio = new javax.swing.JTextArea();
        txtAdreca = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtTipus = new javax.swing.JTextField();
        txtModalitats = new javax.swing.JTextField();
        txtServeis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnlImatges = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentaris = new javax.swing.JTextArea();
        lblValoracio = new javax.swing.JLabel();
        pnlNewComment = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNewComment = new javax.swing.JTextArea();
        cmbValoracio = new javax.swing.JComboBox<>();
        btnComment = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        pnlComentaris = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNom.setText("nom");
        txtNom.setEnabled(false);

        txtDescripcio.setColumns(20);
        txtDescripcio.setRows(5);
        txtDescripcio.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcio);

        txtAdreca.setText("adreca");
        txtAdreca.setEnabled(false);

        txtEmail.setText("email");
        txtEmail.setEnabled(false);

        txtWeb.setText("web");
        txtWeb.setEnabled(false);

        txtTelefon.setText("telefon");
        txtTelefon.setEnabled(false);

        txtTipus.setText("tipus");
        txtTipus.setEnabled(false);

        txtModalitats.setText("modalitats");
        txtModalitats.setEnabled(false);

        txtServeis.setText("serveis");
        txtServeis.setEnabled(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnlImatges.setBorder(javax.swing.BorderFactory.createTitledBorder("imatges"));
        pnlImatges.setLayout(new javax.swing.BoxLayout(pnlImatges, javax.swing.BoxLayout.Y_AXIS));

        txtComentaris.setColumns(20);
        txtComentaris.setRows(5);
        jScrollPane2.setViewportView(txtComentaris);

        lblValoracio.setText("jLabel1");

        txtNewComment.setColumns(20);
        txtNewComment.setRows(5);
        jScrollPane3.setViewportView(txtNewComment);

        cmbValoracio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        btnComment.setText("Comment");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewCommentLayout = new javax.swing.GroupLayout(pnlNewComment);
        pnlNewComment.setLayout(pnlNewCommentLayout);
        pnlNewCommentLayout.setHorizontalGroup(
            pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlNewCommentLayout.createSequentialGroup()
                        .addComponent(cmbValoracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComment)))
                .addContainerGap())
        );
        pnlNewCommentLayout.setVerticalGroup(
            pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlNewCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbValoracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComment))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pnlComentaris.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlComentaris.setLayout(new javax.swing.BoxLayout(pnlComentaris, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane5.setViewportView(pnlComentaris);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtTipus, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(133, 133, 133))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtModalitats, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlImatges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtServeis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblValoracio)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(pnlNewComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblValoracio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdreca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtModalitats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtServeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pnlImatges, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlNewComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(227, 227, 227))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtTipus.setText(espai.getTipus());
        txtNom.setText(espai.getNom());
        txtDescripcio.setText(espai.getDescripcio());
        txtAdreca.setText(espai.getAdreca() + ", " + espai.getMunicipi());
        txtTelefon.setText(espai.getTelefon());
        txtEmail.setText(espai.getEmail());
        txtWeb.setText(espai.getWeb());
        loadImages();
        loadComments();
        loadValoracioAvg();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        DataAccess da = new DataAccess();
        SessionSingleton session = SessionSingleton.INSTANCE.getInstance();
        
        int result = da.insertComentariEspai(txtNewComment.getText(),
                session.getUsuari().getId(), espai.getRegistre(),
                Integer.parseInt(cmbValoracio.getSelectedItem().toString()));
        loadComments();
    }//GEN-LAST:event_btnCommentActionPerformed

    private void loadImages() {
        DataAccess da = new DataAccess();
        txtModalitats.setText(da.getModalitatsEspai(espai.getRegistre()).toString());
        txtServeis.setText(da.getServeisEspai(espai.getRegistre()).toString());
        ArrayList<byte[]> imatges = da.getImatgesEspai(espai.getRegistre());
        for (byte[] binaryImage : imatges) {
            ImageIcon imatge = new ImageIcon(binaryImage);
            JLabel lblImatge = new JLabel();
            lblImatge.setText("");
            lblImatge.setSize(Constants.DEFAULT_PROFILE_IMAGE_WIDTH, Constants.DEFAULT_PROFILE_IMAGE_HEIGHT);
            lblImatge.setIcon(imatge);
            pnlImatges.add(lblImatge);
        }
        pack();
    }

    private void loadComments() {
        DataAccess da = new DataAccess();
        ArrayList<Comentari> comentaris = da.getComentarisEspai(espai.getRegistre());
        
        for(Comentari comentari: comentaris) {
            ComentariComponent comentariComponent = new ComentariComponent();
            comentariComponent.setComentari(comentari);
            pnlComentaris.add(comentariComponent);
        }

//        txtComentaris.setText("");
//        for (String comentari: comentaris) {
//            txtComentaris.append(comentari + "\n\n");
//        }
    }
    
    private void loadValoracioAvg() {
        DataAccess da = new DataAccess();
        float valoracioAvg = da.getValoracioEspaiAvg(espai.getRegistre());
        lblValoracio.setText("Valoració mitjana: " + String.format("%.1f", valoracioAvg));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaiDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspaiDetailsDialog dialog = new EspaiDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JComboBox<String> cmbValoracio;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblValoracio;
    private javax.swing.JPanel pnlComentaris;
    private javax.swing.JPanel pnlImatges;
    private javax.swing.JPanel pnlNewComment;
    private javax.swing.JTextField txtAdreca;
    private javax.swing.JTextArea txtComentaris;
    private javax.swing.JTextArea txtDescripcio;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtModalitats;
    private javax.swing.JTextArea txtNewComment;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtServeis;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtTipus;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
